#GENERAL PURPOSE DEFAULT CONFIG
#NOT NEEDED

REDIS_SERVER_IP: redis-service
REDIS_SERVER_PASSWORD: ''
REDIS_SERVER_PORT: 6379


authorizationTokenHeaderName: Authorization
authorizationTokenPrefix: Bearer
endpoints:
    cors:
        allowed-headers: '*'
        allowed-methods: '*'
        allowed-origins: '*'
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://discovery-service:9000/eureka}
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
expirationTime: 864000000
management:
    endpoints:
        web:
            exposure:
                include: beans,health,routes,httptrace,mappings


spring:
    devtools:
        restart:
            enabled: true
    jpa:
        database: MYSQL
        database-platform: 'org.hibernate.dialect.MySQL8Dialect '
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
    redis:
        host: redis-service
        jedis:
            pool:
                max-active: 40
                max-idle: 30
                max-wait: 10000
                min-idle: 10
        password: ''
        port: 9736
        timeout: 10000
    session:
        redis:
            flush-mode: 'on-save'


# Token secret config
tokenSecret: hfgry463hf746hf573ydh475fhy5739


