KT_SERVICE_IP: kt-service
NOTE_MYSQL_DB_HOST: database-service
NOTE_MYSQL_DB_NAME: krysznatec
NOTE_MYSQL_DB_PORT: 3306
api:
    zuul:
        actuator:
            url:
                path: /actuator/*
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_DATABASE_PASSWORD:possibility@3733}
        url: jdbc:mysql://database-service:3306/krysznatec?useSSL=true&autoReconnect=true
        username: ${MYSQL_DATABASE_USER:matome}

zuul:
    host:
        connect-timeout-millis: 600000
        socket-timeout-millis: 600000
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    ignored-services: '*'
    routes:
        awsservice:
            path: /api-aws/**
            serviceId: awsservice
            stripPrefix: false
            url: http://localhost:9002
        azureservice:
            path: /api-azure/**
            serviceId: azureservice
            stripPrefix: false
            url: http://localhost:9003
        cloudgateway:
            path: /api-gateway/**
            serviceId: cloudgateway
            stripPrefix: false
        ibmservice:
            path: /api-ibm/**
            serviceId: ibmservice
            stripPrefix: false
            url: http://localhost:9004
        ktservice:
            path: /api/**
            serviceId: ktservice
            stripPrefix: false
            url: http://${KT_SERVICE_IP}:9005
    sensitive-headers: Cookie,Set-Cookie


