NOTE_MYSQL_DB_HOST: database-service
NOTE_MYSQL_DB_NAME: krysznatec
NOTE_MYSQL_DB_PORT: 3306
api:
    zuul:
        actuator:
            url:
                path: /actuator/*
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_DATABASE_PASSWORD:krysznatec@2021}
        url: jdbc:mysql://database-service:3306/krysznatec?useSSL=true&autoReconnect=true
        username: ${MYSQL_DATABASE_USER:krysznatec}
    cloud:
        discovery:
            enabled: true

zuul:
    host:
        connect-timeout-millis: 600000
        socket-timeout-millis: 600000
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    ignored-services: '*'
    routes:
        awsservice:
            path: /api-aws/**
            serviceId: AWS-SERVICE
            stripPrefix: false
            url: http://aws-service:9002
        azureservice:
            path: /api-azure/**
            serviceId: AZURE-SERVICE
            stripPrefix: false
            url: http://azure-service:9003
        CLOUD-GATEWAY:
            path: /api-gateway/**
            serviceId: CLOUD-GATEWAY
            stripPrefix: false
            url: http://gateway-service:9001
        ibmservice:
            path: /api-ibm/**
            serviceId: IBM-SERVICE
            stripPrefix: false
            url: http://ibm-service:9004
        DECISION-ENGINE:
            path: /api/**
            serviceId: DECISION-ENGINE
            stripPrefix: false
            url: http://krysznatec-service:9005
    sensitive-headers: Cookie,Set-Cookie


